name: Build & Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dew-portofolio

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with: 
        path: code
    - name: Checkout site
      uses: actions/checkout@v2
      with: 
        token: ${{ secrets.MY_TOKEN }}
        repository: deonetwo/deonetwo.github.io
        ref: master 
        path: site
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - run: npm install
    - run: npm run build --if-present
    - name: Clean website
      run: |
        pushd site
        git rm -rf .
        popd
    - name: Copy site
      run: |
        pushd site
        cp -rvf ../code/.next/* . 
        popd
        ls -la site/ 
    - name: Publish
      run: |
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global user.name "github-actions"
        pushd site 
        git add . 
        git commit -m "next build from Action ${GITHUB_SHA}" 
        git push origin master
        popd
